# Generated by Django 3.1.7 on 2021-03-20 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprofile',
            old_name='doctor',
            new_name='patient',
        ),
    ]
