# Generated by Django 3.1.7 on 2021-03-20 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20210320_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprofile',
            old_name='description',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='qualification1',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='qualification2',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='qualification3',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='years',
        ),
    ]
