# Generated by Django 3.1.7 on 2021-03-20 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('years', models.CharField(blank=True, max_length=200, null=True)),
                ('qualification1', models.CharField(blank=True, max_length=200, null=True)),
                ('qualification2', models.CharField(blank=True, max_length=200, null=True)),
                ('qualification3', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('nurse', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
